export const myData = [
    {
        id: 1,
        img: "https://hosty.xxx/i/adafa095fca1b1c9fcb94233062c5eb1d218db2d.jpg",
        cost: 115.00,
        title: "DENIM STA PATTERN BIG APE HEAD  MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 2,
        img: "https://hosty.xxx/i/c67fc130f8a90c39a9a3e7ccfad41c60fe14db89.jpg",
        cost: 125.00,
        title: "DENIM STA PATTERN BIG APE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 3,
        img: "https://hosty.xxx/i/c6d2d58e2484d1358e69c173ee82093d24ed8020.jpg",
        cost: 245.00,
        title: "STA PATTERN LOOSE FIT DENIM PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 4,
        img: "https://hosty.xxx/i/519ff09b01e06eb85c03a05a7c18b48c71ee7a04.jpg",
        cost: 345.00,
        title: "BAPE STA ",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 5,
        img: "https://hosty.xxx/i/229ec436f1b08efc858b1f232d1ec3e515e7f166.jpg",
        cost: 245.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 6,
        img: "https://hosty.xxx/i/eb418cc3f062f41665405736c275304eee92b581.jpg",
        cost: 345.00,
        title: "BAPE STA  LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
     isfavourite: false,
        type: "Footwear",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 7,
        img: "https://hosty.xxx/i/b56c682b61e1021f1cf11a7894999565998f84f5.jpg",
        cost: 345.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 8,
        img: "https://hosty.xxx/i/f8ce247f47c365e5dfa154e839c22e1dbd15fe23.jpg",
        cost: 245.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 9,
        img: "https://hosty.xxx/i/f820ae29894b4affe094c646c20a70c412d240c0.jpg",
        cost: 115.00,
        title: "APE HEAD MULTI PRINT TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: true,
        trend: false,
    },


    {
        id: 10,
        img: "https://hosty.xxx/i/f895a7ac6f55356210843a8a63e838baf9e969c7.jpg",
        cost: 345.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 11,
        img: "https://hosty.xxx/i/079258bcf258852f49bbace13a1ea54fe0642467.jpg",
        cost: 345.00,
        title: "BAPE STA LADIESpe",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 12,
        img: "https://hosty.xxx/i/720b1d66474f1134bf503fbd6f09dcc2e32e86af.jpg",
        cost: 245.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 13,
        img: "https://hosty.xxx/i/d39576dfeb8f0cde39e462e9721df2d6c1542a45.jpg",
        cost: 245.00,
        title: "BAPE STA #3 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 14,
        img: "https://hosty.xxx/i/ef2eefd349feda8bbd55664ffdd1c3c3b2a92f0e.jpg",
        cost: 245.00,
        title: "BAPE STA #1 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: true,
        new: false,
        trend: false,
    },


    {
        id: 15,
        img: "https://hosty.xxx/i/ace95379e636a873fc1663ac7068e4b6b3d550b8.jpg",
        cost: 345.00,
        title: "BAPE STA #5 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 16,
        img: "https://hosty.xxx/i/6f5a381855c8355b6535e6661746f0fb75ca567f.jpg",
        cost: 15.00,
        title: "1ST CAMO IPHONE 12 / 12 PRO CASE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 17,
        img: "https://hosty.xxx/i/5363115fbc0a0373fa649029760d1f70a5a04ac9.jpg",
        cost: 14.00,
        title: "1ST CAMO IPHONE 12 / 12 PRO CASE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 18,
        img: "https://hosty.xxx/i/da1f748fbad998d3b918aa4a6ddd06ea2811cb8c.jpg",
        cost: 14.00,
        title: "1ST CAMO IPHONE 12 / 12 PRO CASE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 19,
        img: "https://hosty.xxx/i/229ec436f1b08efc858b1f232d1ec3e515e7f166.jpg",
        cost: 345.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 20,
        img: "https://hosty.xxx/i/4313f4f09323ea703034fba80572944d721e78dd.jpg",
        cost: 15.00,
        title: "1ST CAMO IPHONE 12 / 12 PRO CASE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 21,
        img: "https://hosty.xxx/i/8d4cbee1fbef1e251da3167074c08afe8f79c0b5.jpg",
        cost: 15.00,
        title: "1ST CAMO IPHONE 12 / 12 PRO CASE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 22,
        img: "https://hosty.xxx/i/3810b4477df3e8c614f5db516614390f14ef3ad9.jpg",
        cost: 15.00,
        title: "APE HEAD MULTI PRINT TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 23,
        img: "https://hosty.xxx/i/473d4018f759c30f1ddf61a77f9da24f5832b46e.jpg",
        cost: 15.00,
        title: "1ST CAMO IPHONE 12 / 12 PRO CASE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 24,
        img: "https://hosty.xxx/i/a1739b976eb201d12f29239db6552fc38a2edc84.jpg",
        cost: 115.00,
        title: "APE HEAD MULTI PRINT TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 25,
        img: "https://hosty.xxx/i/4f17f1be2da77ff283878058a85cd72d4a2468fc.jpg",
        cost: 125.00,
        title: "APE HEAD MULTI PRINT TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 26,
        img: "https://hosty.xxx/i/87ee2ea74c7709ee84269a4f0227e89c41a994fb.jpg",
        cost: 135.00,
        title: "COLOR CAMO SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 27,
        img: "https://hosty.xxx/i/96940e766eb75110b180367c0a9e004bfe2f787a.jpg",
        cost: 135.00,
        title: "COLOR CAMO SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 28,
        img: "https://hosty.xxx/i/b5cc54b91d16c0c9c7a589d4ab687c30a02b9d44.jpg",
        cost: 135.00,
        title: "DENIM STA PATTERN BIG APE HEAD TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 29,
        img: "https://hosty.xxx/i/4f2af9c6968716cc48aeec0bc38736b70963dd7b.jpg",
        cost: 145.00,
        title: "DENIM STA PATTERN BIG APE HEAD TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 30,
        img: "https://hosty.xxx/i/86b77cced52b2ba1cd523ad8e71a12517e0e9d8b.jpg",
        cost: 105.00,
        title: "DENIM STA PATTERN BIG APE HEAD TEE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 31,
        img: "https://hosty.xxx/i/c994efc445fd2d481cdffdf159ee405fcf91b4ce.jpg",
        cost: 125.00,
        title: "STA PATTERN LOOSE FIT DENIM  MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: false,
    },

    {
        id: 32,
        img: "https://hosty.xxx/i/ae6878022eddad9508ac9932093fb0fd60df8584.jpg",
        cost: 115.00,
        title: "STA PATTERN LOOSE FIT DENIM  MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 33,
        img: "https://hosty.xxx/i/1a7076ca64b79673b2d7ca16b0166fbe13f6ecd9.jpg",
        cost: 235.00,
        title: "BAPE CHECK SHARK HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 34,
        img: "https://hosty.xxx/i/3de863f27326dc303129435a6fd4084ed60f35e6.jpg",
        cost: 155.00,
        title: "BAPE CHECK SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 35,
        img: "https://hosty.xxx/i/a216c3c05817a74c2e9efcee83f107c0686a9029.jpg",
        cost: 195.00,
        title: "BAPE CHECK SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 36,
        img: "https://hosty.xxx/i/8d3a8cb83d47ae1d884a28c8081efa4fced330b3.jpg",
        cost: 185.00,
        title: "BAPE CHECK SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 37,
        img: "https://hosty.xxx/i/0c732b10099256d0bd33338380e190ca36cb1ebb.jpg",
        cost: 165.00,
        title: "BAPE CHECK SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 38,
        img: "https://hosty.xxx/i/4e800596a038eab126d181452c869634bc4a0212.jpg",
        cost: 245.00,
        title: "BAPE FOR MANS",
        content: "BAPE CHECK SHARK FULL ZIP HOODIE MENSqwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 39,
        img: "https://hosty.xxx/i/6ade8f91355a0d7a4e5a294c392758a8bed6288f.jpg",
        cost: 255.00,
        title: "APPLIQUE WIDE CREWNECK LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 40,
        img: "https://hosty.xxx/i/f2e0da41bbeb284d0d131da2fe4f69b6468c987d.jpg",
        cost: 235.00,
        title: "APPLIQUE WIDE CREWNECK LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 41,
        img: "https://hosty.xxx/i/a2a07d27d1c6d115aaacc47ea5b588cd2f14e597.jpg",
        cost: 215.00,
        title: "APPLIQUE WIDE CREWNECK LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },

    {
        id: 42,
        img: "https://hosty.xxx/i/656540fd588b970e5beb30fae96c939790f4cb30.jpg",
        cost: 225.00,
        title: "APPLIQUE WIDE CREWNECK LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 43,
        img: "https://hosty.xxx/i/b5e40cbd5a963b3e148e7ddd510a37e0c7112384.jpg",
        cost: 155.00,
        title: "BABY MILO RELAXED FIT CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 44,
        img: "https://hosty.xxx/i/687f9ce1a0930ad9c6b526f855a8b7c18f181529.jpg",
        cost: 245.00,
        title: "1ST CAMO SLIM SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 45,
        img: "https://hosty.xxx/i/3ff52b27699f1f5568bd12eeb9d76fb6c0125108.jpg",
        cost: 225.00,
        title: "1ST CAMO SLIM SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 46,
        img: "https://hosty.xxx/i/6db686e1ffdf86a332015afbcc105fc3f578b010.jpg",
        cost: 245.00,
        title: "1ST CAMO SLIM SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 47,
        img: "https://hosty.xxx/i/153e75b2bd31cff38c6c8113c132dedc72069985.jpg",
        cost: 245.00,
        title: "1ST CAMO SLIM SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 48,
        img: "https://hosty.xxx/i/1aa83f1941f68bd4f200c0bc6fac801730572905.jpg",
        cost: 215.00,
        title: "1ST CAMO SLIM SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 49,
        img: "https://hosty.xxx/i/2fa8effa53ba6991d9b71dec6a8894d92e9863bb.jpg",
        cost: 195.00,
        title: "1ST CAMO SWEAT PANTS M BAPEC MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 50,
        img: "https://hosty.xxx/i/0efaabf0c2c2be9d7f2ca2992628330b1571cee5.jpg",
        cost: 175.00,
        title: "1ST CAMO SWEAT PANTS M BAPEC MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 51,
        img: "https://hosty.xxx/i/31738dc47d570e30e25d31418affad5fa64f8346.jpg",
        cost: 175.00,
        title: "1ST CAMO SWEAT PANTS M BAPEC MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: true,
        new: false,
        trend: false,
    },

    {
        id: 52,
        img: "https://hosty.xxx/i/a08bf7cc07b2e81920f0dbd4d762df56facd18eb.jpg",
        cost: 185.00,
        title: "1ST CAMO MULTI POCKET SHORTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 53,
        img: "https://hosty.xxx/i/2f60274575afca51928dc05c5181fd002a4df8b6.jpg",
        cost: 195.00,
        title: "1ST CAMO MULTI POCKET SHORTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 54,
        img: "https://hosty.xxx/i/c1558228c642e55849e7255d7210322eef3f1df3.jpg",
        cost: 235.00,
        title: "ABC CAMO SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 55,
        img: "https://hosty.xxx/i/52abf7a8d4d350fadfc830432c6e3e066dd901da.jpg",
        cost: 215.00,
        title: "ABC CAMO SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 56,
        img: "https://hosty.xxx/i/53a17b3438854c1c3af1ade0c505bc3b4b10dcc5.jpg",
        cost: 215.00,
        title: "ABC CAMO SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 57,
        img: "https://hosty.xxx/i/254ceefd19ce5c28804d5d87dc477f665f3e3c53.jpg",
        cost: 245.00,
        title: "ABC CAMO SWEAT PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: true,
        new: true,
        trend: false,
    },
    {
        id: 58,
        img: "https://hosty.xxx/i/fa6f72ef784aba7711b48a029600cbba3e87c7fb.jpg",
        cost: 245.00,
        title: "1ST CAMO MULTI POCKET SHORTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 59,
        img: "https://hosty.xxx/i/f3971161a92b2d1ac76edc22691d91388e12f7f3.jpg",
        cost: 145.00,
        title: "CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 60,
        img: "https://hosty.xxx/i/7acfa509c23198a8d93417662a3f3bd3f30763d9.jpg",
        cost: 145.00,
        title: "1ST CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 61,
        img: "https://hosty.xxx/i/0b85269415690ab1106d6222035903f747862f03.jpg",
        cost: 145.00,
        title: "1ST CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: false,
    },

    {
        id: 62,
        img: "https://hosty.xxx/i/3a0d9e73054d1728f114143ca5054892edd41c32.jpg",
        cost: 145.00,
        title: "1ST CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 63,
        img: "https://hosty.xxx/i/5de2eefec1092df5ddf33ca31ecb132b99122c7d.jpg",
        cost: 145.00,
        title: "CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 64,
        img: "https://hosty.xxx/i/2cf13da732d13effdbdcc19726fc5ed643d7fcda.jpg",
        cost: 145.00,
        title: "1ST CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 65,
        img: "https://hosty.xxx/i/371310f81d3b39a0a6de10156a4b9fbfb9d0d670.jpg",
        cost: 145.00,
        title: "1ST CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: true,
    },
    {
        id: 66,
        img: "https://hosty.xxx/i/f820ae29894b4affe094c646c20a70c412d240c0.jpg",
        cost: 145.00,
        title: "1ST CAMO BY BATHING APE CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: true,
        new: false,
        trend: true,
    },
    {
        id: 67,
        img: "https://hosty.xxx/i/70ab49a30d0981e816a60e0075e8dc403fb76e91.jpg",
        cost: 95.00,
        title: "RANDOM BAPE STA RELAXED POLO MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 68,
        img: "https://hosty.xxx/i/3a0d9e73054d1728f114143ca5054892edd41c32.jpg",
        cost: 135.00,
        title: "BABY MILO FRIENDS ZIP HOODIE KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 69,
        img: "https://hosty.xxx/i/fd72b0716ccbdd7e02c3424e30effb7c59a395dd.jpg",
        cost: 145.00,
        title: "APE HEAD KNIT BODY ZIP HOODIE JR KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 70,
        img: "https://hosty.xxx/i/dc2e2ca9d76413876cd0c83ba242e05e579fcb12.jpg",
        cost: 145.00,
        title: "SHARK SHOULDER ZIP HOODIE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 71,
        img: "https://hosty.xxx/i/d3d5a8b06a6237805f5b0a0b37a896518cae9a8a.jpg",
        cost: 145.00,
        title: "SHARK SHOULDER ZIP HOODIE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },

    {
        id: 72,
        img: "https://hosty.xxx/i/7ec227aa7e2c426d66e0ff52bdb1f1991a27c862.jpg",
        cost: 145.00,
        title: "SHARK SHOULDER ZIP HOODIE BLUE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 73,
        img: "https://hosty.xxx/i/2487df06e4e6b0cad415bb1b4d7066fd4b58355c.jpg",
        cost: 195.00,
        title: "1ST CAMO SHARK SHOULDER ZIP HOODIE KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 74,
        img: "https://hosty.xxx/i/2002192f73b071f9109815d36081bbc6b3144182.jpg",
        cost: 156.00,
        title: "3ST CAMO SHARK SHOULDER ZIP HOODIE KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 75,
        img: "https://hosty.xxx/i/34ffbb28c0ee0c59d42d97a0bb4f141f99885bd8.jpg",
        cost: 121.00,
        title: "2ST CAMO SHARK SHOULDER ZIP HOODIE KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 76,
        img: "https://hosty.xxx/i/5203db07e7d8c01c4c9052cb13849c68e9fc0c41.jpg",
        cost: 111.00,
        title: "1ST CAMO SHARK SHOULDER ZIP HOODIE KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 77,
        img: "https://hosty.xxx/i/235859e6344de3949a3c85cd14a019490c08a45c.jpg",
        cost: 275.00,
        title: "1ST CAMO BELT EASY PANTS MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Pants",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 78,
        img: "https://hosty.xxx/i/767b8baa27e2d7c088198962f827e9b1d9f889a9.jpg",
        cost: 189.00,
        title: "1ST CAMO BIG LOGO HOODIE JACKET KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 79,
        img: "https://hosty.xxx/i/a674c0bab48ee0c849bc5aef7b0fd3b8f05ccda3.jpg",
        cost: 145.00,
        title: "1ST CAMO BIG LOGO HOODIE JACKET KIDS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 80,
        img: "https://hosty.xxx/i/3c9b6c17de85c21dc6c6cbe8be5027b6af72c5e8.jpg",
        cost: 385.00,
        title: "COLOR CAMO ISLAND SLIPPER",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 81,
        img: "https://hosty.xxx/i/a2c035c117dec1ec02d808faf3364a20af3fd14f.jpg",
        cost: 365.00,
        title: "COLOR CAMO ISLAND SLIPPER",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },

    {
        id: 82,
        img: "https://hosty.xxx/i/8ebd04001018559e7968ddf7d998e21633972974.jpg",
        cost: 345.00,
        title: "BAPE STA #2 LADIES",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 83,
        img: "https://hosty.xxx/i/fd73e309e887583f0d3eab052e4777da53e57a4a.jpg",
        cost: 145.00,
        title: "BAPE CHECK LOOSEFIT CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 84,
        img: "https://hosty.xxx/i/bbfc4b90895595b2fa5d55b09f3a20b5808d0f39.jpg",
        cost: 245.00,
        title: "BAPE STA LOGO CREWNECK MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "CUT AND SEWN",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 85,
        img: "https://hosty.xxx/i/da8a90615b0ca79ab22b2ebddb3e3809a1b495f4.jpg",
        cost: 105.00,
        title: "ABC CAMO AIRPODS CASE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 86,
        img: "https://hosty.xxx/i/fd0959eee7bce87d3b153f9ebc38f8751d6f3472.jpg",
        cost: 175.00,
        title: "TYPE 4 BAPEX MEN",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 87,
        img: "https://hosty.xxx/i/d56f740e346b394567ae7193d47b31b90d2965cc.jpg",
        cost: 175.00,
        title: "TYPE 4 BAPEX MEN",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 88,
        img: "https://hosty.xxx/i/3613bb8cc679f36532f277360b8b4c3d8252bf41.jpg",
        cost: 175.00,
        title: "TYPE 4 BAPEX MEN",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 89,
        img: "https://hosty.xxx/i/af333b5054bb0774ea32dc18d925601db02e4665.jpg",
        cost: 175.00,
        title: "ABC CAMO AIRPODS CASE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 90,
        img: "https://hosty.xxx/i/34f054bc03b03cfbd479baa6d30a27f90691434e.jpg",
        cost: 165.00,
        title: "SHARK PULLOVER HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: false,
    },

    {
        id: 91,
        img: "https://hosty.xxx/i/a2c035c117dec1ec02d808faf3364a20af3fd14f.jpg",
        cost: 355.00,
        title: "BAPE FOOTWEAR",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: false,
        new: true,
        trend: false,
    },

    {
        id: 92,
        img: "https://hosty.xxx/i/8ebd04001018559e7968ddf7d998e21633972974.jpg",
        cost: 345.00,
        title: "EXOTIC FOOTWEAR",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Footwear",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 93,
        img: "https://hosty.xxx/i/fd73e309e887583f0d3eab052e4777da53e57a4a.jpg",
        cost: 99.00,
        title: "BAPE MANS HOODIE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 94,
        img: "https://hosty.xxx/i/bbfc4b90895595b2fa5d55b09f3a20b5808d0f39.jpg",
        cost: 975.00,
        title: "BAPE FOR MENS ",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: true,
        trend: false,

    },
    {
        id: 95,
        img: "https://hosty.xxx/i/da8a90615b0ca79ab22b2ebddb3e3809a1b495f4.jpg",
        cost: 195.00,
        title: "ABC CAMO AIRPODS CASE",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 96,
        img: "https://hosty.xxx/i/fd0959eee7bce87d3b153f9ebc38f8751d6f3472.jpg",
        cost: 195.00,
        title: "TYPE 4 BAPEX MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: true,
        trend: false,
    },
    {
        id: 97,
        img: "https://hosty.xxx/i/d56f740e346b394567ae7193d47b31b90d2965cc.jpg",
        cost: 195.00,
        title: "TYPE 4 BAPEX MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: true,
        new: false,
        trend: false,
    },
    {
        id: 98,
        img: "https://hosty.xxx/i/3613bb8cc679f36532f277360b8b4c3d8252bf41.jpg",
        cost: 195.00,
        title: "STYPE 4 BAPEX MEN",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "Accessories",
        sales: false,
        new: false,
        trend: true,
    },
    {
        id: 99,
        img: "https://hosty.xxx/i/f820ae29894b4affe094c646c20a70c412d240c0.jpg",
        cost: 175.00,
        title: "COLOR CAMO SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: false,
        trend: false,
    },
    {
        id: 100,
        img: "https://hosty.xxx/i/596356176fda161b93e50bd260574c3450368938.jpg",
        cost: 445.00,
        title: "COLOR CAMO SHARK FULL ZIP HOODIE MENS",
        content: "qwertyuiopasdfghjklzxcvbnm",
        isfavourite: false,
        type: "T-SHIRTS",
        sales: false,
        new: true,
        trend: false,
    }

    ]
export default myData;